[package]
name = "wasm-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.99"
aes-gcm = "0.10.3"
base64 = "0.22.1"
pbkdf2 = "0.12.2"
sha2 = "0.10"
hmac = "0.12"
rand = "0.8"
[lib]
crate-type = ["cdylib"]